[build]
  # Build configuration for React + Vite
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  # Node.js version for build
  NODE_VERSION = "18"

# SPA redirect rule - catch all routes and serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # HTTPS and security headers
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CORS headers for API access
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Caching for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific configuration
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  # Use test keys for deploy previews
  VITE_SUPABASE_URL = "https://pdmtvkcxnqysujnpcnyh.supabase.co"
  # VITE_SUPABASE_ANON_KEY = "your-test-anon-key"
  # VITE_STRIPE_PUBLISHABLE_KEY = "pk_test_your-test-publishable-key"
  # VITE_STRIPE_COFFEE_PRICE_ID = "price_your-test-coffee-price-id"

# Form handling (if needed for future contact forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Function configuration (for Netlify Functions if we add them later)
[functions]
  directory = "netlify/functions"
  included_files = ["node_modules/**"]

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

# Production build optimization
[context.production]
  command = "npm run build"